### ISSUE TITLE
Is there a way to remove the downward arrow of the tabbar, on top right?

### ISSUE THREAD

**Issue by 5h10** [Neikon/Fox11#7]
![Screenshot (423)](https://github.com/Neikon/Fox11/assets/95940673/7783a28e-f04f-482c-af3e-caaa4c1d764d)

**Comment by Neikon** [comment]
add to userchrome.css this code
```css
#alltabs-button{
   display: none;
}
```
