### ISSUE TITLE
[Question] Disabling the 3 color dots for the normal exit, maximize and minimize buttens

### ISSUE THREAD

**Issue by CJWagner2002** [Neikon/Fox11#9]
Where in the files can you disable the new colored buttons for in favor of the default ones.

**Comment by Neikon** [comment]
components/round_caption_buttons.css
you can deactivate it by commenting it  in userChrome.css
```css
/* ############# Required files ############## */
/* coment/uncoment  to enable/disable*/

/* @import url('components/mica_support.css'); */ /* Deprecate in Firefox 117  */
/* @import url('components/hide_alltabs_button.css'); */
@import url('components/autohide_bookmarks_and_main_toolbars.css');
@import url('components/urlbar_centered_text.css');
/* @import url('components/round_caption_buttons.css');  */   <<==============================
@import url('components/toolbars.css');
@import url('components/vivaldifox.css');
/* @import url('components/adaptative_tab_bar_color.css'); */


/* ############# Personal Settings ############## */
#navigator-toolbox{--uc-autohide-toolbar-delay: 100ms; /* The toolbar is hidden after 0.1s */}
:root{   
   --general-border-radius: 8px !important;
   --auto-general-color: var(--lwt-accent-color) !important;
}
```
